services:
  mongodb:
    restart: unless-stopped
    image: mongo:latest
    init: true
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 5s
      retries: 5

  redis:
    restart: unless-stopped
    image: redis:alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 5

  rabbitmq:
    restart: unless-stopped
    build:
      context: ./monitoring/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    environment:
      - RABBITMQ_ERLANG_COOKIE=socialmedia_secret_cookie
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
  api-gateway:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./api-gateway/Dockerfile
    ports:
      - "3000:3000"
    env_file: ./api-gateway/.env
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - IDENTITY_SERVICE_URL=http://identity-service:3001
      - POST_SERVICE_URL=http://post-service:3002
      - NOTIFICATION_SERVICE_URL=http://notification-service:3003
      - MEDIA_SERVICE_URL=http://media-service:3004
      - SEARCH_SERVICE_URL=http://search-service:3005
      - COMMENT_SERVICE_URL=http://comment-service:3006
      - CHAT_SERVICE_URL=http://chat-service:3007
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 5

  identity-service:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./identity-service/Dockerfile
    env_file: ./identity-service/.env
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/identity_db
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 5s
      retries: 5

  post-service:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./post-service/Dockerfile
    env_file: ./post-service/.env
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/post_db
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3002/health"]
      interval: 30s
      timeout: 5s
      retries: 5

  comment-service:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./comment-service/Dockerfile
    env_file: ./comment-service/.env
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/comment_db
      - RABBITMQ_URL=amqp://rabbitmq:5672
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3006/health"]
      interval: 30s
      timeout: 5s
      retries: 5

  media-service:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./media-service/Dockerfile
    env_file: ./media-service/.env
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/media_db
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3004/health"]
      interval: 30s
      timeout: 5s
      retries: 5

  search-service:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./search-service/Dockerfile
    env_file: ./search-service/.env
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/search_db
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3005/health"]
      interval: 30s
      timeout: 5s
      retries: 5

  notification-service:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./notification-service/Dockerfile
    env_file: ./notification-service/.env
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/notification_db
      - RABBITMQ_URL=amqp://rabbitmq:5672
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3003/health"]
      interval: 30s
      timeout: 5s
      retries: 5

  chat-service:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./chat-service/Dockerfile
    env_file: ./chat-service/.env
    ports:
      - "4000:4000"
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/chat_db
      - RABBITMQ_URL=amqp://rabbitmq:5672
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3007/health"]
      interval: 30s
      timeout: 5s
      retries: 5


  prometheus:
    restart: unless-stopped
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    restart: unless-stopped
    image: grafana/grafana:latest
    ports:
      - "3050:3000"
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  mongodb_data:
